### ISSUE TITLE
Quest Bugs

### ISSUE THREAD

**Issue by ghost** [JadedPacks/Agrarian-Skies-2#1]
- [x] Nether star quest in first chapter ??
- [x] Nether star quest in "Storage Wars" chapter.
- [x] Nether star quest in "For the hoarding"
- [x] Add quest icon for "First Steps"
- [x] Add more description on how to use BQM in "First Steps" (e.g. second tab for claiming rewards)
- [x] Change requirement of "Getting Equipment" Flint axe head -> Wood axe head
- [x] Remove blank pattern requirement in "Getting Equipment" (Required anyway to craft the items?)
- [x] Fix name tag coloring in quests (e.g. "First Steps")
- [x] "Singing in the rain" add dependency on "Hammer Time"
- [x] Remove clay reward from "Hammer Time"
- [x] "Hammer Time" grammar mistake
- [x] "Hammer Time", explain how to get gravel, sand, dust...

**Comment by Ozzymud** [comment]
Change requirement of "Getting Equipment" Flint axe head -> Wood axe head  

This change is incompatible with the tinkers materials blacklist. Wood/cobble were never a valid tool head materials in AS2. This should be returned to flint imo.
