### ISSUE TITLE
Stone Cold Killing

### ISSUE THREAD

**Issue by CesarUlises1996** [JadedPacks/Agrarian-Skies-2#100]
## Bug Report

dont work the quest (dont detect it) 
By: Stone Cold Killing - Sky Farm

## Steps to Reproduce (for bugs)

1.craft stone killer and animal filter upgrade
2.both aren't complete in the book

## Logs

* Client/Server Log:

## Client Information

* Modpack Version: last one (29-07-2020)
* Server/LAN/Single Player:Single player

**Comment by remclave** [comment]
Which version of the pack do you have installed?

**Comment by CesarUlises1996** [comment]
2.0.6 i have crafted the items two times and didn't work (no complete in the quest book)

**Comment by remclave** [comment]
There is another quest that must be completed before that one will complete. Have you begun blood magic yet?

**Comment by CesarUlises1996** [comment]
i gonna play with others mods fisrt, actually im learning about Big reactor, so this quest going to wait, i did the quest of the "Mail Order Catalogue" in a first intent to try to fix it but still nothing.
Nice and thanks for you support dude and i guest when i get blood magic complet, if it isnt working yet, i gonna put a new comment below or a new one issue "in the case of u wanna clean this problem in github", and while im getting progressive if it is fixed, i gonna close the link about "my bug" if  is still open?.  i hoppe u understand me, my english isnt good xd.

**Comment by remclave** [comment]
Hint: start by visiting the mob hunter chapter and killing squiddies.
