### ISSUE TITLE
No recipe for "The Rod of the Terra Firma" from Botania in AS2 v2.0.6.

### ISSUE THREAD

**Issue by CesarUlises1996** [JadedPacks/Agrarian-Skies-2#101]
## Bug Report

There is no recipe in NEI. Placing the recipe manually in a crafting Station and Terminal (AE2)  also does not work. 
This item is required from quest.

## Steps to Reproduce (for bugs)

1.Search "Agricultural Journal" in NEI.
2.No recipe appears
3.Placing the recipe manually
I take the crafting from Lexica Botania and The Wiki as a reference, also Compare the runes id to not be wrong.

https://github.com/CesarUlises1996/Bugs/blob/master/Crafting%20Station.png
https://github.com/CesarUlises1996/Bugs/blob/master/Terminal.png

## Logs

* Client/Server Log:

## Client Information

* Modpack Version:2.0.6
* Server/LAN/Single Player:Single Player

**Comment by tecrogue** [comment]
The quest requesting this should have been removed already as the recipe was intentionally removed. Did you run the "bq_admin default load" command after updating to 2.0.6?

**Comment by CesarUlises1996** [comment]
The mission is still there. 
I don't know where that command is put :(
The launcher i use is from twitch

**Comment by tecrogue** [comment]
The command can be run after opening the game to LAN and enabling cheats. 

Once you have done that you can put it in the chat without the "s and with a / in front of it to run the command.

**Comment by CesarUlises1996** [comment]
does this enable crafting or will it remove the quest?

**Comment by remclave** [comment]
I just confirmed that the quest is NOT part of the 2.0.6 update. Run the command as specified by techrogue.

**Comment by remclave** [comment]
"The Rod of the Terra Firma" was considered too OP for the style of the pack and was removed by the lead modpack dev. It will not be included in any future updates.

**Comment by CesarUlises1996** [comment]
fix it:
bq_admin default load
