### ISSUE TITLE
Mature Sesame Seeds Seed Plant crashes the game when right-clicking with Wooden Hand Rake

### ISSUE THREAD

**Issue by Pirous** [JadedPacks/Agrarian-Skies-2#102]
## Steps to Reproduce

1. Plant Sesame Seeds Seed
2. Let it grow up till it becomes 100% grown, mature
3. Right click with Wooden Hand Rake
4. Game crashes. (Fortunately, it doesn't corrupt save, game restores to the moment just before rake use.)

## Logs

* Crash Log:
https://pastebin.com/JQDCQDi4
## Client Information

* Modpack Version: 2.0.6
* Server/LAN/Single Player: Single Player

**Comment by remclave** [comment]
This is a long-standing bug from the early versions of Pam's Harvestcraft. In addition, the crop does not drop sesame seeds. There are no fixes for these bugs.
