### ISSUE TITLE
is it a bug ?

### ISSUE THREAD

**Issue by CesarUlises1996** [JadedPacks/Agrarian-Skies-2#103]
## Bug Report

I'm not pretty sure if it is a bug, but i kill to gaia guardian (II), so many times, and i cant get the "will of Dharok", i mean this is so hard to get something like 0.1% to get the item.
I really need "good luck"
Fight with him is really tired beacuse he cant hurt me, but is hard get hit him
i have not more terrasteal and  i  have finish all about botania (quest)

## Steps to Reproduce (for bugs)

1.KILL TO GAIA 2 AND NOT GET THE ITEM
2.CRY
3.TRY AGAIN T_T

https://github.com/CesarUlises1996/Bugs/blob/master/QUEST.png?raw=true
https://github.com/CesarUlises1996/Bugs/blob/master/GAIA%202.png?raw=true

## Logs

* Client/Server Log:

## Client Information

* Modpack Version:2.0.6 (last one)
* Server/LAN/Single Player: Single Player

**Comment by remclave** [comment]
This is not a bug. It really is that difficult. During testing, I eventually acquired all of the Wills. Perseverance and luck in rng is your only option.
