### ISSUE TITLE
Rubber tree

### ISSUE THREAD

**Issue by quinten1442** [JadedPacks/Agrarian-Skies-2#104]
I planted my rubber sapling i got from a quest and after it grew i went to break it using the raiding hoe i got from the old mcdonald quest. But even though WAILA told me i could break it it wouldnt break.

**Comment by remclave** [comment]
This is not a bug. The raiding hoe will not break logs. Instead, a tool made with metals specifically designed to chop the rubber wood, copper or bronze iirc, is required. This is done on purpose to move players from using the raiding hoe as a one-size-fits-all solution.
