### ISSUE TITLE
Crash Game

### ISSUE THREAD

**Issue by Ingnotic** [JadedPacks/Agrarian-Skies-2#112]
## Steps to Reproduce

1. Start game and receive a message that game crashec (Exit code: 0)
2. Image: https://pasteboard.co/FJwEPOn6gh3G.png

## Logs

* Crash Log: https://pastebin.com/kwWwQr4i

## Client Information

* Modpack Version: 2.0.6
* Server/LAN/Single Player: Single Player

**Comment by tecrogue** [comment]
Looks like the pack didn't download/install properly. Recommendation would be to repair/reinstall the pack.

**Comment by 1765924238** [comment]
从新下载也不行

**Comment by Ingnotic** [comment]
Sorry for late's reply. I downloaded it directly from Curseforge so how can it didn't download properly. I have tried twice

**Comment by tecrogue** [comment]
When your launcher downloads the mods during initial setup, sometimes they don't download them properly, or sometimes they don't properly download forge. It can happen either because of your network connection having an issue during the install, or the servers having an issue during.

**Comment by Ingnotic** [comment]
But i have been crashed and i have downloaded it again but it still happened

**Comment by Ingnotic** [comment]
i repair it and it still crashed

**Comment by tecrogue** [comment]
"it crashed again" doesn't give us any info, when did it crash and we need new crash logs to see what the current crash is.

If it crashed when you opened your inventory the first time, that is a known issue and only happens once.
