### ISSUE TITLE
Game crashes after opening Forge Lexicon

### ISSUE THREAD

**Issue by a1d4r** [JadedPacks/Agrarian-Skies-2#14]
## Steps to Reproduce
Open Forge Lexicon (ID: 4352)

## Logs
https://pastebin.com/8SfwfnKv

## Client Information
* Modpack Version: 2.0.1
* Single Player

**Comment by ghost** [comment]
Not replicatable... ?

**Comment by a1d4r** [comment]
I don't know why, but my game crash everytime I try to open this book. I tested it in 3 different created world.

**Comment by ghost** [comment]
It sounds more like a client issue. Maybe running out of memory or othewise? We have had over 5 different users test this, and all manage to get it working fine.
