### ISSUE TITLE
not really a bug but the new curse launcher sucks

### ISSUE THREAD

**Issue by kamyflouge** [JadedPacks/Agrarian-Skies-2#16]
so about the hotfix update 2.0.1 update you posted. id really appreciated if you made the the file downloadable as a zip because ever since the curse launcher changed i cant download files and cmpdl doesnt work either. thanks

**Comment by tecrogue** [comment]
The download from curseforge should still work

https://www.curseforge.com/minecraft/modpacks/agrarian-skies-2/files/2729270
