### ISSUE TITLE
Quest issue; Mob Hunter - Brain Bashing.

### ISSUE THREAD

**Issue by RubikMonat** [JadedPacks/Agrarian-Skies-2#17]
## Bug Report
Kill 5x Thaumcraft Brainy Zombie not incrementing. 

## Steps to Reproduce (for bugs)
1. Kill zombies once quest is unlocked.  
2. Counter does not go up past 0

## Logs
N/A

## Client Information
* Modpack Version: 2.0?
* Server/LAN/Single Player: Single player

Maybe just make it a requirement to have some of the brain item instead?

**Comment by ghost** [comment]
Tested with killing brainy zombies, and giant brainy zombies. Both are detecting on the quest?

**Comment by RubikMonat** [comment]
I have over two stacks of brains, and zombies removed all 33 trapdoors from my mobfarm so I'm sure I'm killing them. Will try a fresh install of the pack.

**Comment by ghost** [comment]
Regular zombies also drop brains. Make sure you are actually killing brainy zombies

**Comment by RubikMonat** [comment]
650+ zombies killed. Statistically very unlikely to get 0 brainy zombies in that lot.
