### ISSUE TITLE
[request] adding crushing recipes to compressed blocks

### ISSUE THREAD

**Issue by kamyflouge** [JadedPacks/Agrarian-Skies-2#19]
I know the mod ex compressum has compressed hammers and sieves but even a simple recipe change would help remedy the early (gravel/sand/dust/) making grind , before you automate them.

**Comment by ghost** [comment]
Assuming you mean breaking with a hammer? Try using the Router Reborn's Vein Hammer. Alternatively, if you're playing in singleplayer, we won't ashame you if you add VeinMiner.
This pack is designed to be a little extra "hardcore", so we won't add it by default.
