### ISSUE TITLE
Quest icons are too close

### ISSUE THREAD

**Issue by a1d4r** [JadedPacks/Agrarian-Skies-2#24]
## Bug Report
Quest icons are too close

## Steps to Reproduce (for bugs)
Open questbook -> Learning Skyblock

## Screenshots
[Questbook](https://i.imgur.com/FnUPavk.jpg)

## Client Information
* Modpack Version: 88e703ebe655effa947bdb09c55dc17ba5d84bd1
* Single Player

**Comment by ghost** [comment]
Yupo, getting resolved :D LOL.
