### ISSUE TITLE
Blank Slate quest requires Hoarders quest

### ISSUE THREAD

**Issue by a1d4r** [JadedPacks/Agrarian-Skies-2#25]
## Bug Report
Blank Slate quest (Mystical Blood) requires Hoarders quest (For the Hoarding). But there is said that hoarders quests are not required to complete the map.

## Client Information
* Modpack Version: 88e703ebe655effa947bdb09c55dc17ba5d84bd1
* Single Player:

**Comment by a1d4r** [comment]
Purity quest (Botanical Engineering) also requires Hoarders, but to complete Hoarders I need 4 manasteel ingots.

**Comment by ghost** [comment]
- [x] Arcane Crafting (Applied Engineering / Thaumaturgy)
- [x] Blank Slate (For the Hoarding / Mystical Blood)
- [x] Purity (Botanical Engineering / For the Hoarding)
