### ISSUE TITLE
Suggestion: Passive mobs quest

### ISSUE THREAD

**Issue by a1d4r** [JadedPacks/Agrarian-Skies-2#27]
## Suggestion
I've been trying to understand why animals are not spawning on my large lit grass area. I think it is worth noting that [common animal mobs do not spawn in desert, badlands, beach, snowy tundra, river, ocean, and mushroom fields biomes](https://minecraft.gamepedia.com/Spawn#Animals)

## Client Information

* Modpack Version: 2.0.4
* Single Player:

**Comment by ghost** [comment]
Animals /should/ spawn, due to JadedOceanSpawns. However, if this is still persisting after a period of time, let me know and I can relook at it?

**Comment by a1d4r** [comment]
Could you please explain how to install the newest version? I copied everything from the repository (except .git files) in the game folder and [the game just don't run](https://i.imgur.com/1CEf8Wt.png).

**Comment by tecrogue** [comment]
When updating you need to remove the old version of mods as well or else you end up with duplicates like that. Delete the non-Jaded Patched version of Agricraft.

**Comment by a1d4r** [comment]
Thanks, the game is running, but I still don't see any animals.

**Comment by ghost** [comment]
Have you updated the "Jaded OceanSpawns" mod? I have tested it, and it does indeed work.

**Comment by a1d4r** [comment]
How can I update it?

**Comment by ghost** [comment]
Inside of hte twitch launcher, unlock the profile, and hit the update icon next to the mod :)

**Comment by a1d4r** [comment]
[Here they are](https://i.imgur.com/oDqHGV8.png). I'm glad to see them although they want to kill me :)
