### ISSUE TITLE
Quest "Arcane Crafting" in Thaumaturgy branch requires "Essentia Storage" quest completed

### ISSUE THREAD

**Issue by DavidYawata** [JadedPacks/Agrarian-Skies-2#28]
I was confused by this, so I looked it up, and apparently there are two quests called "Arcane Crafting", one in Thaumaturgy, and one in Applied Engineering. The Thaumaturgy one is supposed to be unlocked right after you start the Thaumaturgy section, but is gated behind the AE quest that has nothing to do with it.

**Comment by ghost** [comment]
In future, please use the format as noted. This was fixed in the 2.0.2 update, so yeh >.>

**Comment by DavidYawata** [comment]
My apologies, I both missed the fact that I was on an outdated version, and somehow didn't see the formats when I created the issue. My bad on both parts, thanks for the assistance!
