### ISSUE TITLE
Can't mine cobalt or ardite with manyullyn mining level tools

### ISSUE THREAD

**Issue by EMatzke1** [JadedPacks/Agrarian-Skies-2#32]
## Bug Report

Whenever using a tool with a mining level of manyullyn to mine cobalt or ardite ore will result in both ores being unable to be mined. 
## Steps to Reproduce (for bugs)

1. Make any tinkers' construct tool with a manyullyn mining level (how else are you going to have that high of a mining level).
2. Attempt to mine cobalt or ardite ore with said tool. 

Any tools that specifically state that they have a cobalt or ardite mining level can mine them respectively (cobalt can mine both).

I am not quite sure if any other blocks which require ardite or cobalt mining levels are affected as I have not come across any other blocks that require such mining level. 
## Logs

* Client/Server Log:

## Client Information

* Modpack Version: 2.0.4
* Server/LAN/Single Player: Server

**Comment by ghost** [comment]
This was fixed as of; https://github.com/JadedPacks/Agrarian-Skies-2/commit/40764852a38519654f61f83b4bedde78765a5d5f#diff-2d7e3af46dda4853e121609796fb81e6R26

**Comment by edohebert12** [comment]
I am currently using version 2.0.4 of AS2 and am encountering the same problem. I am using an enderium pickage (harvest level Manyullyn) which can mine nether diamond ore, but neither cobalt nor ardite ore.
