### ISSUE TITLE
Placing Leadstone Energy Cell causes crash

### ISSUE THREAD

**Issue by crpmax** [JadedPacks/Agrarian-Skies-2#34]
## Steps to Reproduce
Placed Leadstone Energy Cell, that I received from quest (Power Storage) or Loot Chest
## Logs 
https://pastebin.com/jgfi1Exy

## Client Information
* Modpack Version: 2.0.4
* Playing on Server
##
After login, the Energy Cell was duplicated, one in the inventory, one placed.
I've tried removing Optifine, like the log suggested, but still same.

**Comment by ghost** [comment]
Quest was fixed, try doing a `/bq_admin default load`, and delete the bugged energy cell.
