### ISSUE TITLE
Stone level sword

### ISSUE THREAD

**Issue by a1d4r** [JadedPacks/Agrarian-Skies-2#35]
## Bug Report
A stone killer requires a stone level sword for it to work. But I can't find any stone level swords available to make. It's impossible to do a sword made of stone parts. The next available material is quartz, but a quartz sword is not stone level. ([screenshot: all available materials](https://i.imgur.com/Dsa0avT.png))

## Client Information
* Modpack Version: 6c0f4bc9851748a0d7fc1ececfb08a0456eca31e
* Single Player

**Comment by a1d4r** [comment]
With a sword made of pink slime it is working, but I don't think I would need a stone killer if I've already made pink slime from MFR.

**Comment by WilxGaming** [comment]
Did you try flint?

**Comment by a1d4r** [comment]
I did. A sword blade cannot be made of flint.
