### ISSUE TITLE
It is not possible to make a endearing heavy plate (TConstruct).

### ISSUE THREAD

**Issue by fenex101** [JadedPacks/Agrarian-Skies-2#36]
As I wrote above. It is not possible to make a endearing heavy plate. Probably, they did not register in (cast heavy plate).

**Comment by tecrogue** [comment]
Please include the following information per the template:

## Bug Report


## Steps to Reproduce (for bugs)

1.
2.


## Logs


* Client/Server Log:

## Client Information

* Modpack Version:
* Server/LAN/Single Player:

**Comment by ghost** [comment]
This item is intentionally disabled by Iguana Tinker Tweaks. To see what materials are available, hold shift over the cast and it will tell you =]
