### ISSUE TITLE
Tinkers parts that can't be made showing in NEI

### ISSUE THREAD

**Issue by WilxGaming** [JadedPacks/Agrarian-Skies-2#37]
For example a Plastic Axe Head shows in NEI, but can't be made. The \config\IguanaTinkerTweaks\restrictions.cfg is blocking it. This problem has been around since 1.1.14.

A Plastic Axe Head would be the highest durability stone level tool for a Chopper.

**Comment by a1d4r** [comment]
Also 4796:598 cannot be made

**Comment by a1d4r** [comment]
+ A lot of parts made from enderium and lumium.
