### ISSUE TITLE
reproducible crash on minecraft launch

### ISSUE THREAD

**Issue by Antsy555** [JadedPacks/Agrarian-Skies-2#38]
I have been playing agrarian skies 2 now for a week or two. After some time successfully playing (maybe 2-3 days), the game will no longer make it to the main menu, crashing everytime forge attempts to load giving this error message: net.minecraft.client.renderer.StitcherException: Unable to fit: thaumcraft:runeborder - size: 64x64 - Maybe try a lowerresolution resourcepack?

I have previously fixed it by reinstalling the pack and moving my save file over, but I can't be bothered to keep having to do that. So I was wondering if there was an easy permanent fix.

## Steps to Reproduce

1. open agrarian skies 2 from twitch launcher
2. launch game from minecraft launcher
3. crashes on texture compiling stage of forge loading

## Logs

* Crash Log:
 https://pastebin.com/get8HCrX
## Client Information

* Modpack Version: 2.0.4
* Server/LAN/Single Player: N/A crashes before game starts

**Comment by ghost** [comment]
YEh, this is a standard minecraft issue and not something we can "fix". Its due to the GPU running out of memory or the likes. Only recommendations I can give is make sure your graphics drivers are up to date :/ Sorry for the inability to help too much.

**Comment by Antsy555** [comment]
> YEh, this is a standard minecraft issue and not something we can "fix". Its due to the GPU running out of memory or the likes. Only recommendations I can give is make sure your graphics drivers are up to date :/ Sorry for the inability to help too much.

Aight np.

Though its almost certainly not a memory issue as it goes away upon reinstall
