### ISSUE TITLE
Error to update the modpack in twitch

### ISSUE THREAD

**Issue by ViniSouRei** [JadedPacks/Agrarian-Skies-2#40]
Cannot find file System.Linq.Enumerable+WhereSelectListIterator`2[Curse.Radium.Minecraft.Models.ManifestResource,System.Int32] for addon 238003 in database. Aborting installation.

this is text that appears to me after twitch cancel the installation

**Comment by ghost** [comment]
Issue with the twitch launcher. Please report the bug with them.
