### ISSUE TITLE
vein hammer dosen't work

### ISSUE THREAD

**Issue by VeineMineaurion** [JadedPacks/Agrarian-Skies-2#42]
## Bug Report

the breaking animation of a block reset at the last moment 
## Steps to Reproduce (for bugs)

1.craft a vein hammer
2.try to "hammer" a block 

## Client Information

* Modpack Version: 2.0.4
* Server/LAN/Single Player: (agrarian.mineaurion.com)

**Comment by ghost** [comment]
This is going to involve some decompiling to work out what's actually going on, and may need to push a patched version if it continues to be silly ^-^

**Comment by ghost** [comment]
Okay, can't seem to find the issue in the code. And not going to bother dobfuscating it as its not open-source, so just going to make the item uncraftable :/ shame :(

**Comment by VeineMineaurion** [comment]
like i said on discord the vein hammer worked pre2.0

**Comment by ghost** [comment]
Literally spent 6 hours working on that fix, so hope you love me for it. >.>
