### ISSUE TITLE
The game crashes after breaking a block of dust using Flux-Infused Hammer

### ISSUE THREAD

**Issue by a1d4r** [JadedPacks/Agrarian-Skies-2#49]
## Steps to Reproduce

1. Put a block of dust
2. Break it with Flux-Infused Hammer

## Logs

* Crash Logs: 
[Server](https://pastebin.com/pDQXt3Fc) 
[Client](https://pastebin.com/tFFTFd2c)

## Client Information

* Modpack Version: 2.0.4
* Single Player

**Comment by ghost** [comment]
Is this a repeatable occurance, or once in a while?

**Comment by a1d4r** [comment]
repeatable
