### ISSUE TITLE
Map updates

### ISSUE THREAD

**Issue by ghost** [JadedPacks/Agrarian-Skies-2#5]
- [x] Regenerate mod lists
- [x] Morvy Cottage map is empty?
- [x] Remove starting chests

**Comment by Ozzymud** [comment]
I had this issue last time I updated the pack. It was missing then, had to go back to Agrarian Skies 2-1.1.8.zip to play with the cottage.

**Comment by tecrogue** [comment]
Morvy Cottage map generated properly just now, weird.

**Comment by tecrogue** [comment]
- [x] Sweet Reminisce generates with cheats enabled
- [x] All that remains generates with cheats enabled
