### ISSUE TITLE
Game doesn't let me enter any multiplayer server

### ISSUE THREAD

**Issue by LanNzao** [JadedPacks/Agrarian-Skies-2#50]
Yesterday, 5th August, i installed agrarian skies 2 to play with my friends in a multiplayer server and all of them already had this modpack and i only installed yesterday and all the servers that i tried to enter never let me in because of a problem of incompatible mods. I think that with the new version of the Agrarian Skies 2, there are a lot of mods that are not suposed to be in there.

Please help,
LanNzao
![Bug Minecraft](https://user-images.githubusercontent.com/53818983/62533281-34831600-b83e-11e9-9fe9-fbd64cb10841.JPG)

**Comment by ghost** [comment]
Server or client is either outdated and incompatable with each version. MAke sure the versions match.,

**Comment by LanNzao** [comment]
> Server or client is either outdated and incompatable with each version. MAke sure the versions match.,

How can i do that using twitch launcher?

**Comment by ghost** [comment]
Well find out which version the server is running, and run the same version on your client?
