### ISSUE TITLE
Alchemical Smelting quest requires Arcane Crafting quest

### ISSUE THREAD

**Issue by a1d4r** [JadedPacks/Agrarian-Skies-2#51]
## Bug Report

Alchemical Smelting [Thaumaturgy] requires Arcane Crafting [Applied Engineering]

## Client Information

* Modpack Version: 02672a29591a94e62665ff21ad1484cc9469070b
* Single Player

**Comment by ghost** [comment]
Fixed by Remclave in dev (Quest files are not uploaded yet due to... secrets?)

**Comment by ori-sky** [comment]
I've also encountered this bug and I was wondering if there's a simple workaround for server owners in the meantime, that would allow players to progress with the quest line without needing to wait for the next release?

**Comment by ghost** [comment]
Have you updated to the latest release and did '/bq_admin default load'

**Comment by ori-sky** [comment]
Hadn't run `/bq_admin default load`, it seems to work now after running that command. Thanks!
