### ISSUE TITLE
Mod Rejections using the most current versions of Agrarian Skies 2

### ISSUE THREAD

**Issue by konnorkoch** [JadedPacks/Agrarian-Skies-2#54]
Using latest version, 2.0.4, on the twitch app for modpack and for server going to curse/twitch site to download server for 2.0.4 and i am running into this mod rejection. I can provide anything else if needed!
![modissues](https://user-images.githubusercontent.com/49297357/65721053-4c755a00-e077-11e9-8522-f63fc3b8c5fb.PNG)

**Comment by ghost** [comment]
Client and server appears to have different mod versions. Try uploading the versions of them mods off your client to the server.
