### ISSUE TITLE
Duplication glitch using BiblioCraft's Armor Stand

### ISSUE THREAD

**Issue by Yowims** [JadedPacks/Agrarian-Skies-2#56]
## Bug Report
When I swapped my Primordial Armor with my Flux-Infused Armor in the Armor Stand, the Flux-Infused Armor disappeared and the Primordial Armor was duplicated.

This image represents the steps I managed to get to this glitch. But I don't know why, the glitch only appeared once :
![test](https://user-images.githubusercontent.com/28302626/67907765-58be6c80-fb79-11e9-8da7-e03241ae1246.png)
The enchants in the duplicated Primordial Armor were here but removed after the glitch, to test if something will happen on the duplicated armor, but nothing relevant.

Here are the details from every piece of equipment :

Primordial Helm - Ordo : Translucency II, Illumine Lens, Goggles of Revealing
Primordial Cuirass - Ordo : Translucency I
Primordial Greaves - Ordo : Translucency I
Primordial Boots - Ordo : Translucency I

Flux-Infused Armor : Protection IV

## Logs
I'm using a corporate Minecraft Launcher, so I don't have any logs to provide.

## Client Information
* Modpack Version: Agrarian Skies 2 - v2.0.4 - 10.13.4.1614
* Server/LAN/Single Player: Appeared on Mineaurion server : agrarian.mineaurion.com

**Comment by ghost** [comment]
Not something we can effectively fix. I'll add it to a backlog of issues I can take a look at for possible patches in the future if I get a breakthrough.
