### ISSUE TITLE
silkworm

### ISSUE THREAD

**Issue by theabadonedlemon** [JadedPacks/Agrarian-Skies-2#57]
## Bug Report

ive gone through 4 crooks and a stack of bonemeal and i cant get a single silk work
## Steps to Reproduce (for bugs)

1.
2.

its also telling me that 80 items are missing when i start a game
## Logs

* Client/Server Log:

## Client Information

* Modpack Version:2.0.4
* Server/LAN/Single Player: single player

**Comment by ghost** [comment]
Missing items are expected. As for the silk work, that's REALLY bad RNG, but they do indeed drop.
