### ISSUE TITLE
Crashes before game even starts (2.0.4)

### ISSUE THREAD

**Issue by Jodmc** [JadedPacks/Agrarian-Skies-2#58]
## Steps to Reproduce

1. Install AS2 through Twitch.
2. Hit "Play" in Twitch, then "Play" in the Minecraft launcher that pops up.
3. Crash ensues.
 - Have tried reinstalling the modpack, crash keeps happening even after re-installing.
 - Graphics Drivers are fully up-to-date (updated before running modpack).
GPU: AMD R7 200 Series (Software: Adrenalin 19.12.2)

## Logs

* Crash Log:https://pastebin.com/4D5YFU0C

## Client Information

* Modpack Version: 2.0.4
* Server/LAN/Single Player: N/A (Crashed before game started)

**Comment by ghost** [comment]
"If you get that error (or the same error but with a different file), we can not help you with it as that is a launcher issue. A known work-around is to download the file from the listed URL in the error and then place it in the listed folder"

**Comment by Jodmc** [comment]
> "If you get that error (or the same error but with a different file), we can not help you with it as that is a launcher issue. A known work-around is to download the file from the listed URL in the error and then place it in the listed folder"

I did this, and I managed to get past the launcher phase (manually downloaded "jopt-simple-4.5.jar" and put in the folder).

However, afterwards I was immediately hit with this:
![image](https://user-images.githubusercontent.com/33239325/70749436-93273780-1ce9-11ea-8783-2162179948f1.png)

I managed to get past that as well by downloading the link it suggested and putting in mods folder, but I shouldn't have gotten either of these in the first place... I have an active internet connection, perfectly stable. It shouldn't be struggling to download a simple jar.

**Comment by ghost** [comment]
MAke sure you're running java 8 :)

**Comment by tecrogue** [comment]
Unfortunately, we have no control over the launcher, Mojang's servers, or
the Forge servers.

**Comment by Jodmc** [comment]
> Make sure you're running java 8 :)

I am using Java 8, even using the most recent recommended version (Version 8 Update 231)


> Unfortunately, we have no control over the launcher, Mojang's servers, or the Forge servers.

So absolutely nothing can be done about this?

**Comment by tecrogue** [comment]
Nothing that we can, as the error happens at the launcher level before the pack loads.

Believe me I wish that wasn't the case since it has been a thorn in our side for the last couple of weeks when it suddenly started.
