### ISSUE TITLE
Blocks Missing

### ISSUE THREAD

**Issue by Jodmc** [JadedPacks/Agrarian-Skies-2#59]
## Bug Report

Blocks are constantly "missing"

## Steps to Reproduce (for bugs)

(continuation of #58, after everything has been fixed and game has been started)
1. Go to Singleplayer > Create New World
2. Create world with All That Remains - Hard
3. Get warned that blocks are missing.
![image](https://user-images.githubusercontent.com/33239325/70753661-83f8b780-1cf2-11ea-89d6-28cc12d738cb.png)
Java and Graphics Driver are both up-to-date. using Windows 10.

## Logs

* Client/Server Log: https://pastebin.com/Q9qrCjKs
(contains everything from the moment of clicking "Create New World" until the popup in screenshot appears while generating)

## Client Information

* Modpack Version: 2.0.4
* Server/LAN/Single Player: Single Player

**Comment by ghost** [comment]
Maps need to be regenerated. Aware of this, and fixed in next version.

**Comment by tecrogue** [comment]
In the meanwhile, just hit Yes. It won't mess up anything.

**Comment by Jodmc** [comment]
> In the meanwhile, just hit Yes. It won't mess up anything.

I did this and it seems to have messed up a lot... pretty much every block is missing aside from water, a round glowstone, some brown block, glass, and a door without any wall around it. In short, there's holes pretty much everywhere, unless that's how the hard mode preset is supposed to look.

Will need to re-start game for screenshot.

**Comment by tecrogue** [comment]
>  pretty much every block is missing aside from water, a round glowstone, some brown block, glass, and a door without any wall around it. In short, there's holes pretty much everywhere, unless that's how the hard mode preset is supposed to look.

That is exactly how that map looks. 

The others are more traditional skyblock/platforms.

**Comment by tecrogue** [comment]
reopening for now for preset regen unless Paws wants it closed before we finish that.
