### ISSUE TITLE
Wood axe head impossible to get.

### ISSUE THREAD

**Issue by Ozzymud** [JadedPacks/Agrarian-Skies-2#6]
I know this was in a big compilation of bugs in a closed issue https://github.com/JadedPacks/Agrarian-Skies-2/issues/1 but I feel it is important to have on its own as this is a fundamental change to the pack.

Wooden heads were never attainable in the original pack. This used to be flint and be much tougher, after getting some cobble and a wooden hammer to make gravel and get flint.  

This could be changed to bone, it is craftable and easily obtainable after the 1st night in the Morvy Cottage as mobs will spawn up near the water source. That would make it more of an easy button task if that is what your after.  

Possible fix:
In DefaultQuests.json change line 6870 from "Damage": 0 to "Damage": 5 this asks for a bone hatchet head

**Comment by ghost** [comment]
Discussed in discord. Wood tools are nerfed, and enabled.
