### ISSUE TITLE
No recipe for Agricultural Journal from Agricraft in AS2 v2.0.5.

### ISSUE THREAD

**Issue by zachs18** [JadedPacks/Agrarian-Skies-2#60]
## Bug Report
There is no recipe in NEI for the Agricultural Journal from Agricraft. Placing the recipe manually in a crafting bench also does not work. This prevents progress in the "Sky Farm" questline because the "Analyzing Mutations" quest requires an agricultural journal.

## Steps to Reproduce
1. Search "Agricultural Journal" in NEI.
2. Click on the Agricultural Journal.
3. No recipe appears

Or
1. Place 4 Agricraft Crops, 4 seeds, and 1 Book and Quill in a crafting bench with the crops in the corners, the Book and Quill in the center, and the seeds on the edges
3. No item is craftable from this recipe
![2019-12-24_15 47 35](https://user-images.githubusercontent.com/8355914/71425623-d2984100-2664-11ea-8d3f-7d33baa38a67.png)

## Workaround
(For LAN or Single Player)
1. Open world.
2. Open your world to LAN with cheats enabled.
3. `/give <username> AgriCraft:journal`

## Client Information
* Modpack Version: 2.0.5
* Server/LAN/Single Player: LAN (also tested and doesn't work in Single Player, don't have a server to test on)
* Java: OpenJDK Java 8u232

**Comment by Sartorian** [comment]
Same issue on server.
Modpack version 2.0.5
Server
Java SE JRE version 8u162
