### ISSUE TITLE
Missing item Portal-in-box Agrarian Skies 2.0.5

### ISSUE THREAD

**Issue by ZombieXLX** [JadedPacks/Agrarian-Skies-2#61]
## Bug Report
There is no item in NEI for the Portal-in-box from Ex-Astris. This prevents progress in the "Thaumaturgy".

## Steps to Reproduce (for bugs)

1. Search "Portal-in-item" in NEI.
2. No item

![image](https://user-images.githubusercontent.com/9981235/72159208-e9f95d00-33cc-11ea-9c61-9623b20f76ed.png)

![image](https://user-images.githubusercontent.com/9981235/72159222-f1b90180-33cc-11ea-85f2-f2b634e7288a.png)

**Comment by ghost** [comment]
It appears the source on the github was massively outdated, and didn't include that when we patched it. Adding it in shortly :) Will send you a fixed jar so you can continue playing ASAP.

**Comment by ghost** [comment]
Fixed as of https://github.com/JadedPacks/Ex-Astris/commit/ab930526e31e1bedaa5e8a2fb49848b6fdf968d5

Added Eldritch portal
Added ability to spawn eldritch cultists from a doll
Added a (rather expensive) recipe to sieve for pearls :P

**Comment by ghost** [comment]
You can download the new patched version of the mod in the above link ^
