### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by ByronB9948** [JadedPacks/Agrarian-Skies-2#62]
[crash-2020-01-11_13.00.25-server.txt](https://github.com/JadedPacks/Agrarian-Skies-2/files/4049006/crash-2020-01-11_13.00.25-server.txt)
Issue happened when i try to creat the server. i followed all the steps but this file (forge-1.7.10-10.13.4.1614-1.7.10-universal) just randomly closed and crash reports appeared

**Comment by ZombieXLX** [comment]
the client has the same problems

[latest.log](https://github.com/JadedPacks/Agrarian-Skies-2/files/4049143/latest.log)

**Comment by ghost** [comment]
Please download this version and replace it for the time being till I have a free hour to fix things.
https://github.com/JadedPacks/Agrarian-Skies-2/raw/a91c8db1c599c43c47d32367b04644f6ed520ffe/modz/Ex-Astris-1.7.10-1.16-JADED_PATCHED.jar
