### ISSUE TITLE
 Ex-Nihilo Aluminium can't be made into blocks or nuggets when smelted directly

### ISSUE THREAD

**Issue by sqwidders** [JadedPacks/Agrarian-Skies-2#63]
The Ex-Nihilo Aluminium, when processed in anything other than the Tinkers' Smeltery, isn't compatible with the compacting drawers. It only shows the Aluminium bars and nuggets but not the blocks. 
I see it's in the ore dictionary but for some reason the ingots aren't completely synced or something. 
I'm trying to automate resources solely with thermal expansion and instead I've had to put a smeltery in the middle of it.

**Comment by Ozzymud** [comment]
I found that the aluminum dust/gravel/sand **wouldn't pulverize** but would smelt in the redstone furnace.. the aluminum I got from that (Ex Nihilo ingots) would go into a locked compacting drawer already containing the tinkers version (it converts if the drawer already has it).

**Comment by remclave** [comment]
For convenience, the recipe to make a TCon Block of Aluminum from Exnihilo's Aluminum Ingots has been added to the oreDict.zs. It will be updated in the next beta/release.

ETA: No action will be taken to include pulverizing recipes. Use of the Exnihilo hammer (any) will remain the only method for increasing the output from the gravel and sand crafted from the ore pieces and crushed ores.
