### ISSUE TITLE
Ex-Astris Portal-In-Box Don't working

### ISSUE THREAD

**Issue by ZombieXLX** [JadedPacks/Agrarian-Skies-2#65]
1. Craft item without texture.
2. Take him, RM click and him do nothing.
3. Enjoy

![screen1](https://user-images.githubusercontent.com/9981235/72325372-07287700-36be-11ea-98f6-3ce8cff3696f.png)

![screen2](https://user-images.githubusercontent.com/9981235/72325374-07c10d80-36be-11ea-8f0f-18af2b30cdb7.png)

**Comment by ghost** [comment]
"Portal-in-a-Box is an item added by the Ex Astris mod. It can be used to place an Eldritch Portal structure, which normally generate naturally in the world. The item must be used on a flat 7x7 area of Grass Blocks or Dirt Blocks."

Tested, and does work on this type of land. I have however fixed the icon :)

Also added text to the quest book to reflect this.
