### ISSUE TITLE
[2.0.5] Botania flower quests should be OR instead of AND

### ISSUE THREAD

**Issue by trevorjd** [JadedPacks/Agrarian-Skies-2#66]
## Bug Report
Most Botania quests requiring the creation of a flower use AND logic, requiring both a flower AND a floating variant of the same flower. While this could be the work of the Insane One, the Mischevious One or to be fair, the Cruel or Jaded Ones, it seems unnecessary to me.

It is however, obstructive with the Stellar Power & Purity quests as the player hasn't yet been taught how to make floating variants (Mana pool, pasture seed and floating flowers are the three steps following Purity.)

## Steps to Reproduce (for bugs)
n/a

## Logs
n/a

## Client Information

* Modpack Version: 2.0.5
* Server/LAN/Single Player: LAN

---

Question: As a workaround, can I edit the JSON on the server and have the change affect/propagate to all clients? Or would I need to get my players to download and install a custom JSON?

**Comment by ghost** [comment]
Just spoke with our quest writer, and her words are "But floating flowers are better" xD

Yes, you CAN change them on the server and it will sync with the clients. MAke sure to edit the quest file in the WORLD directory, not the CONFIG directory.
