### ISSUE TITLE
2.0.5 "Server Files"

### ISSUE THREAD

**Issue by Draylynn** [JadedPacks/Agrarian-Skies-2#68]
## Bug Report
2.0.5 server files pack contains no manifest or notes on setup for the server files, including which FML build is required. It's an incomplete installation that cannot be utilized with CurseForge-compatible installers and requires digging around the client logs for the relevant information (which not everyone will know how to do).

## Steps to Reproduce (for bugs)
Download the server files.
Open with any ZIP manager.
Profit.

**Comment by ghost** [comment]
Server files don't use a manifest as all the mod jars are built into it.

Yes, we don't provide instructions which is a downside, however there is a page here: https://www.curseforge.com/minecraft/modpacks/agrarian-skies-2/pages/setting-up-an-agrarian-skies-2-server
