### ISSUE TITLE
Crash on open inventory

### ISSUE THREAD

**Issue by sims1253** [JadedPacks/Agrarian-Skies-2#69]
## Steps to Reproduce

1. Install through twitch app
2. Start game, set 60fps limit and remove view bobbing
3. Start game on boni-normal world
4. Press f3 to see fps
5. Open inventory to get rid of tutorial thingy (double press e quickly)
6. crash

## Logs
* Crash Log: https://pastebin.com/CCdTb4hf

## Client Information
* Modpack Version:  Twitch client 2.0.5 (although the menue screen says it is 2.0.4
* Server/LAN/Single Player: Single Player
* Most recent Oracle Java 8 JRE 64bit

**Comment by mezzoEmrys** [comment]
Running into the same issue, but only on fresh install. This happened to my server group on Mac as well as Windows. On the first opening the inventory (whether through crafting or through opening inventory directly), the game hard crashes. This does not happen again afterwards.

**Comment by Ozzymud** [comment]
Can confirm only happens on fresh install, on re-run and after all is well.

**Comment by NabilZaman** [comment]
Also want to add this happened to me and my friend both on our first time playing after an install.

Can anyone confirm this only happens the first-time and doesn't re-occur during their playthrough?

**Comment by remclave** [comment]
Can confirm. Tested multiple times after the INITIAL crash and never had a repeat. Closing this issue as it was originally posted to the NEI github. Due to the age of the mod, it is doubtful we will see it fixed. So we just include the information in the update for each beta/release notes.
