### ISSUE TITLE
Starting chest contents (Morvy Cottage)

### ISSUE THREAD

**Issue by Ozzymud** [JadedPacks/Agrarian-Skies-2#7]
The starting chest is missing some contents, at least from how it used to be. It had several different types of saplings and more bone meal. 

![2019-06-22_22 13 44](https://user-images.githubusercontent.com/6426344/59971998-792b4a00-953b-11e9-97c9-80d03c1aa81a.png)

Screenshot taken from chest on new world from my old install circa 2015

**Comment by Ozzymud** [comment]
This could also be a solution for https://github.com/JadedPacks/Agrarian-Skies-2/issues/6 as a flint axe head was entirely possible as well.

**Comment by Ozzymud** [comment]
Also, if the chest contents are corrected, the apples are not needed as the new map appears to start you with full hunger and half saturation. The old map started you with half hunger.

**Comment by ghost** [comment]
Chests are due to be removed from the maps during the next update. All items are due to be given in starting inventory.
