### ISSUE TITLE
Iguana Tinker Tweaks: Picking up milk with a clay bucket gives you an iron bucket

### ISSUE THREAD

**Issue by LeagueRaINi** [JadedPacks/Agrarian-Skies-2#70]
## Bug Report
Picking up milk with a clay bucked gives u an iron milk bucket

## Steps to Reproduce (for bugs)
1. Pickup milk with clay bucket ([clip](https://i.imgur.com/5Ku5jDv.mp4))

## Logs
* Client/Server Log: ~writes nothing into the log

## Client Information
* Modpack Version: 2.0.5
* Server/LAN/Single Player: Server

**Comment by remclave** [comment]
[Per the mod author](https://github.com/SlimeKnights/IguanaTweaksTConstruct), there will be no further action taken.
