### ISSUE TITLE
Agricultural Journal not craftable?

### ISSUE THREAD

**Issue by ItsJeb** [JadedPacks/Agrarian-Skies-2#71]
## Bug Report

I am trying to craft the agricultural journal and it will not craft, I have tried everything.
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:

## Client Information

* Modpack Version: version 2.0.5
* Server/LAN/Single Player: Single player

**Comment by ghost** [comment]
Please see https://discordapp.com/channels/547865092134535179/584100761097601046/671081539811016716

**Comment by ItsJeb** [comment]
![Screenshot (57)](https://user-images.githubusercontent.com/61809315/75934245-92fa8c00-5e41-11ea-875b-63294fabc6db.png)

**Comment by ItsJeb** [comment]
that discord link sent me to nothing?

**Comment by tecrogue** [comment]
You may need to join the server first:  https://discord.gg/bkyMbv2
