### ISSUE TITLE
Quest Issue: Mystical Blood Quest Line

### ISSUE THREAD

**Issue by TheThorny** [JadedPacks/Agrarian-Skies-2#72]
## Bug Report
Mystical Blood quest  line does not unlock

## Steps to Reproduce (for bugs)

1. Create a new map
2. Complete quests as usual
3. All quest lines unlock except Mystical Blood
4. Create and use Sanguimancy items, path still does not unlock.
5. Quests with prerequisites in Mystical Blood cannot be unlocked or completed (such as most of the Sky Farm quests)

## Logs

* Client/Server Log:
no log
## Client Information

* Modpack Version: 2.0.5
* Server/LAN/Single Player: Single Player

**Comment by mezzoEmrys** [comment]
In version 2.0.5, you have to complete the quest in Mob Hunter to kill squids.

**Comment by remclave** [comment]
mezzoEmrys provided the correct solution.
