### ISSUE TITLE
Server Does Not Open

### ISSUE THREAD

**Issue by ghost** [JadedPacks/Agrarian-Skies-2#75]
Hello.
I've been trying to open an AS2 server to play with my friends. I've done everything that is said at the server opening guide of AS2. But when I start the universal.jar it starts to open but after a while it stucks and nothing happens so server doesn't open and when you try to close it stops responding. I will be glad if you can help me. Thanks!

**Comment by tecrogue** [comment]
Without a sever log file of some sort we have no idea what the issue may be.
