### ISSUE TITLE
"Phancy Phials" quest requires the wrong "Arcane Crafting" per-requisite 

### ISSUE THREAD

**Issue by Ozzymud** [JadedPacks/Agrarian-Skies-2#77]
Version 2.0.5

Got to the Thaumcraft quests and came across the Fancy Phials quest, it was locked and said it needed arcane crafting which I had completed early on in the Thaum line. I was confused so went into edit mode to see what was wrong. I noticed there are 2 quests identically named, one is for the basic thaumcraft crafting table, the other is for the AE crafting grid for Thaum, the latter is the one the phials quest is asking for.  

I renamed the AE one "AE Arcane Crafting" and set the per-requisite for Fancy Phials to the one for the basic crafting table "Arcane Crafting"... Which way is intended? AE seems a lot later then getting some empty phials.

**Comment by tecrogue** [comment]
Corrected in 2.0.6
