### ISSUE TITLE
Botania Quest Flow

### ISSUE THREAD

**Issue by Hillgrove** [JadedPacks/Agrarian-Skies-2#81]
There are some inconsistencies in the Botania quest flow.. it requires a pasture seed before making a mana pool (which is what you use to make a pasture seed).. unless ofc. your intended quest flow is going through bees to get a pasture seed.

**Comment by Ozzymud** [comment]
Can confirm, had to craft a second mana pool and pick up my spreader to get the next 2 quests after pasture seeds as I needed the mana to make said pasture seeds. They should be moved after at minimum the pool/spreader/daybloom in the progression.

**Comment by NabilZaman** [comment]
Seems like this is addressed in a recent commit, https://github.com/JadedPacks/Agrarian-Skies-2/commit/78c2398656c63baef43809b608a4deb35a8d5b86
so probably will be fixed in 2.0.6

**Comment by remclave** [comment]
[Version 2.0.6 beta is now on CurseForge](https://www.curseforge.com/minecraft/modpacks/agrarian-skies-2/files/2978214).
