### ISSUE TITLE
Agricultural journal is not craftable

### ISSUE THREAD

**Issue by Zvezdin** [JadedPacks/Agrarian-Skies-2#83]
## Bug Report

The agricultural journal from AgriCraft is necessary for the quest "Analyzing mutations", yet NEI does not show recipes for it and the ones in the FTB wiki do not work. 

## Steps to Reproduce (for bugs)

Try to craft it.

## Client Information
* Modpack Version: 2.0.5
* Server/LAN/Single Player: SP

**Comment by tecrogue** [comment]
#71 

We have an updated agricraft file on the Jaded Packs Discord that will be included in the next update.  Currently the fixed file can be located via the link in Issue #71

**Comment by tecrogue** [comment]
Fix is added to 2.0.6
