### ISSUE TITLE
AS2 Map does not load

### ISSUE THREAD

**Issue by devmartzn** [JadedPacks/Agrarian-Skies-2#84]
## Bug Report
My AS2 map does not load and I can't play

## Steps to Reproduce (for bugs)

1. https://www.curseforge.com/minecraft/modpacks/agrarian-skies-2
2. then i installed forge http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10_pre4.html
3. after making all correctly i put the folders in *.minecraft* folder
4. started minecraft Forge 1.7.10 and all was correct. No Errors and Minecraft started Correctly.
5. I created a New World in Singleplayer and the map don't loaded

## Client Information

* Modpack Version: 2.0.5

**Comment by tecrogue** [comment]
Which preset did you choose? Also do any of the others work?

**Comment by devmartzn** [comment]
I choose the default preset. But I tried with the other presets and it doesn't work too

**Comment by devmartzn** [comment]
Do I need to re-install it?

**Comment by remclave** [comment]
Try relaunching from scratch first. Sometimes after a map doesn't load, I've done this and was able to get the map to load. Re-installation is a last resort since everything else _appeared_ to have loaded correctly.

**Comment by devmartzn** [comment]
I re-installed all but nothing seems to happen

**Comment by remclave** [comment]
It's been many years since I used the raw building techniques for loading a modpack. Have you tried one of the launchers like (ugh!) Twitch?

**Comment by devmartzn** [comment]
Ok ill try

**Comment by devmartzn** [comment]
Oh, I need Minecraft Launcher Premium

**Comment by devmartzn** [comment]
So I can't
