### ISSUE TITLE
'Assembly Line' hasn't opened

### ISSUE THREAD

**Issue by OBeardedOne** [JadedPacks/Agrarian-Skies-2#85]
I completed all of the quests in 'Learning to Skyblock' and the 'Assembly Line' category hasn't opened up which means I cannot complete other quests due to them being locked by a quest inside Assembly Line. As I don't have permission to type any commands, I wondered if anyone else had any luck in this?

*The quest to open 'Assembly Line' is 'Auto Smashing' in Learning to Skyblock
**I'm playing MC v1.7.10

Thank you!

**Comment by remclave** [comment]
Do you have the most recent version of the mod pack? Some issues with the quest book were corrected. If you have updated your mod pack, you will still need to follow the steps posted on the Jaded Packs discord FAQ channel to update your quest book.

**Comment by OBeardedOne** [comment]
I've just done that and it hasn't seemed to do anything? I'm running the 'Latest Version' from the technic Launcher. I've reinstalled it anyway along with replacing the file for the Quest Book which still hasn't done anything :/ 
It is v2.0.4

**Comment by OBeardedOne** [comment]
I managed to fix it, might have been a typo for my script but I don't know, had to go into the code in Python which had 'Thermal Beginings' with a pre-requisite being a quest that didn't exist, only after changing it to it's proper quest (Simple Storage) did it allow me to unlock Assembly Line when I updated inside the instance.

**Comment by remclave** [comment]
I know you closed this but just wanted to say the Technic Launcher doesn't have the most current version of the mod pack. Version [2.0.5](https://www.curseforge.com/minecraft/modpacks/agrarian-skies-2/files) is the one that works with the updated DefaultQuests.json. The quest should have been linked back to 'Auto Smashing' and does in the current version.

In addition to the above, a newer version is currently being tested before 'release' to ensure we have fixed the persistent issues that keep returning, like 'Herobrine' used to...
