### ISSUE TITLE
Game won't open

### ISSUE THREAD

**Issue by Simshub** [JadedPacks/Agrarian-Skies-2#89]
## Client Information
The Game won't even open and just say 'An unexpected problem occurred and it crashed. We apologize for the inconvenience.' I even tried using the older versions of it, yet nothing worked.
* Modpack Version: 2.0.5

**Comment by remclave** [comment]
download [2.0.6 beta ](https://www.curseforge.com/minecraft/modpacks/agrarian-skies-2/files/2978214)

eta: The failure of the modpack to open is a clientside issue that occurs when not enough memory is assigned to run the instance. Check you java settings in your chosen loader and ensure at least 4G is made available for the pack to run.
