### ISSUE TITLE
Phancy phials quest still asking for wrong arcane crafting quest

### ISSUE THREAD

**Issue by Sylatire** [JadedPacks/Agrarian-Skies-2#90]
So i recently updated the modpack to the 2.0.6 version, where the phancy phials, wand charger and vis relay quests asking for the wrong arcane crafting quest bug should be fixed, but they're still asking for the applied engineering one

Modpack Version: 2.0.6
SinglePlayer world

**Comment by tecrogue** [comment]
Have you used the "bq_admin default load" command as mentioned in the patch notes?

**Comment by Sylatire** [comment]
Yes, and it's still not working. I even tried to create another world, use the command and then completing the quest but nothing seems to work

**Comment by remclave** [comment]
Just saw this: This was supposed to have been fixed. Looking into it now.

**Comment by remclave** [comment]
Fixed. Visit our [discord](https://discord.gg/bkyMbv2) find the updated file in the agrarian-skies-2 Pack Tips and FAQs.

ETA: the updated defaultquests will be added to the next beta/release.
