### ISSUE TITLE
Arcane Crafting Terminal converts ethereal essence to different aspects when withdrawing

### ISSUE THREAD

**Issue by nekizalb** [JadedPacks/Agrarian-Skies-2#93]
## Bug Report
If you withdraw ethereal essence from an Arcane Crafting Terminal when you already have some in your bags, the withdrawn items are added to the existing stack, regardless of the type withdrawn.

## Steps to Reproduce (for bugs)
1. Setup an ME system with 
 - Energy Acceptor (and some provided power. I used an AE creative energy cell for this demo)
 - ME Drive with  1 normal storage cell
 - Crafting Terminal
 - Arcane Crafting Terminal
 - EX: https://i.imgur.com/sv4KLMP.png
2. Deposit a stack of Ethereal essence of one aspect into the ME system. Have 1 item of another type in your inventory (in my example, I have terra deposited and aer in my inventory
 - https://i.imgur.com/KVt6R0m.png
3. Using the (normal) Crafting Terminal, shift click to withdraw the Terra ethereal essence.
  - item correctly withdraws as a separate stack.
 - https://i.imgur.com/meAonEX.png
4. Redeposit the terra and use the Arcane Crafting terminal to shift withdraw a stack.
 - This time, only 63 terra are removed, and added to the aer stack
 - https://i.imgur.com/kHTEo75.png

This conversion can be done between any set of ethereal essences. Once you have a decent wisp farm running, you basically have infinite of all essentia at your fingertips.

This does NOT work if the stack of 1 is on your hotbar, vs your inventory
  - https://i.imgur.com/eihom2q.png

It's not just Ethereal essence. I can do the same with Bees, botania flowers. Appears any item with the same item ID, but not if the items have a different colon notation (3:1 for coarse dirt wont convert to normal dirt for instance, but phials full of essentia, which have an item ID of 5223:1 can be converted to different essentia. You just can't convert them to empty phials (5223)).
 - https://i.imgur.com/i1olSRr.png
 - https://i.imgur.com/tjjIDhH.png

## Logs
No crash logs, just unintended behavior

## Client Information

* Modpack Version: 2.0.5
* Server/LAN/Single Player: Server

**Comment by nekizalb** [comment]
(apologies for the bug spam. When i saw on reddit that there was still maintenance on this pack ongoing, I figured I would share the things I came across in my most recent playthrough)

**Comment by remclave** [comment]
Keep up the bug spam. If we can fix it we will. Do keep in mind, however, we are working with a lot of mods that are no longer updated by the mod authors and their teams. IF we can provide a fix, we will.

**Comment by remclave** [comment]
[This bug ](https://github.com/Nividica/ThaumicEnergistics/issues/387)has already been reported at the Thaumic Energistics github.

**Comment by nekizalb** [comment]
Yeah, I figured it's a decent chance it's not a problem with AS2 specificly, but I don't have the expertise to know for sure if it's a customization or the original mod =) Thanks for sharing.
