### ISSUE TITLE
Is the requirement for blood writing quest supposed to be ME arcane crafting?

### ISSUE THREAD

**Issue by Sylatire** [JadedPacks/Agrarian-Skies-2#94]
So i was about to make my path to the blood wand when I realized that the blood writing, one of the blood wand quest requirements, needed the Arcane Crafting ME Style, which is way too advanced for a scribbing tool. Is this intentional?

**Comment by Sylatire** [comment]
Noticed that someone reported this and the problem has been solved
EDIT: I've updated the modpack and it's still asking for the ME arcane crafting quest

**Comment by remclave** [comment]
Did you remember to run the command "bq_admin default load" ? Because this quest has indeed been fixed in the newest beta and the instructions in the changelog provided this information.

ETA: Gonna double check. I might have actually missed that one.

**Comment by Sylatire** [comment]
I did run the command, and i actually re-installed the update 3 times running at least 2 times the command per each and nothing

**Comment by remclave** [comment]
Okay. I did find that the quest was indeed incorrectly linked. It has been corrected. Visit [our discord](https://discord.gg/bkyMbv2) to download and update your file.

The updated file will be in the next beta/release.
