### ISSUE TITLE
Extra life crafting not working

### ISSUE THREAD

**Issue by Sylatire** [JadedPacks/Agrarian-Skies-2#95]
## Bug Report
The extra life custom recipe on the alchemic chemistry set does not work, i've tried the 3 first tiers of the magic blood orbs, but none seems to work. Plus, NEI shows that you can craft it with tier 2 blood orbs and so on, so it should be working.

## Steps to Reproduce (for bugs)
1.- Enter an agrarian skies 2 world
2.- Try to craft an extra life

## Client Information
* Modpack Version: 2.0.6 beta 2
* Server/LAN/Single Player: Singleplayer

**Comment by remclave** [comment]
Do you have enough LP in your soul network?

**Comment by Sylatire** [comment]
> Do you have enough LP in your soul network?

Yes, as it just only asks for 200 LP

**Comment by remclave** [comment]
I just ran it on my single player world and it worked perfectly. I used the Apprentice Orb and my soul network had 25400 LP when I started. It may need more LP than what is shown.

eta: I'm actually glad I was able to test it in my active game as I already had unlocked the quest but hadn't completed it until now

**Comment by remclave** [comment]
The process consumed 400 LP
