### ISSUE TITLE
Blood wand quest requires trascendent blood orb quest

### ISSUE THREAD

**Issue by Sylatire** [JadedPacks/Agrarian-Skies-2#97]
## Bug Report
The title is self explanatory, but yeah, i think it was intended for it to ask a master blood orb since it's involved in the recipe, but it asks for the trascendent one instead. I did the bq_admin default load thing, but i guess that the problem hasn't been noticed before

## Steps to Reproduce (for bugs)
1. Open the quest book and check the blood wand quest

## Client Information
* Modpack Version: 2.0.6 beta 2
* Server/LAN/Single Player: singleplayer

**Comment by remclave** [comment]
The Blood Wand quest is done this way on purpose. It was established by Developaws and that is the way she wanted it. If you make it earlier, so be it. If I remember right, it is not a crafting quest so it will count simply having it in your inventory at the time the quest is reached.
