### ISSUE TITLE
Trying to eat tinker's chisel

### ISSUE THREAD

**Issue by PixelSupreme** [JadedPacks/Agrarian-Skies-2#99]
## Bug Report
I made a Tinker's Construct chisel out of an invar head and green slime handle. When I right-click into the air with the chisel n hand, the "eating" animation is being played and the chisel GUI does not open. When I right-click a bock with the chisel, the eating animaltion is being played and the blocke gets oaccasionally chiseled.

## Steps to Reproduce (for bugs)
1. Create a chisel with Tinker's Construct parts
2. a) While holding the chisel right-click into the air
2. b) While holding the chisel, right-click a block, for example stone bricks

## Client Information
* Modpack Version: 2.0.6 Beta
* Server/LAN/Single Player: Singleplayer

**Comment by remclave** [comment]
From: ["Tinkers' Construct Wiki"](https://tinkers-construct.fandom.com/wiki/Chisel)

"In the world, you can hold right-click on a block to turn it into its chiseled form, if one is available. For instance, dirt does not have a chiseling recipe. If you are in creative mode, the block will instantly transfrom [sic]. If not, an eating animation will show and the block will be changed."
